### ISSUE TITLE
Licensing Unclear

### ISSUE THREAD

**Issue by albertoantunes** [fiji/3D_Viewer#20]
Hi, I am interested in using a portion of this project, specifically the STLLoader class, but am not sure what license is it under? I tried searching for 3D_Viewer project on this page but couldn't find it: 

https://github.com/fiji/fiji/blob/master/LICENSES

If possible could a license file be added to this project to make it clear?
Thanks

**Comment by acardona** [comment]
As far as I know the STLLoader.java should be GPL, given that the rest of the 3D Viewer code was also GPL. The author @dscho could comment on his code to confirm.

**Comment by ctrueden** [comment]
@acardona Are you sure the 3D Viewer is GPL? I cannot find anything anywhere which declares this. Not this repository, not the [Fiji LICENSES file](https://github.com/fiji/fiji/blob/master/LICENSES), not the [3D Viewer wiki page](http://imagej.net/3D_Viewer), not the [3D Viewer web site](http://132.187.25.13/ij3d/). If you are certain, I will update this repository to declare the code as GPL (v2+? v3+? something else?).

**Comment by bene51** [comment]
We agreed long ago that it should be GPL, latest version. But it's possible that this is not mentioned anywhere. I thought actually it's at least stated in the Fiji LICENSES file, but obviously not.

**Comment by dscho** [comment]
> We agreed long ago that it should be GPL, latest version.

Correct.

**Comment by albertoantunes** [comment]
Thanks for clarifying! Sadly I won't be able to use it then. I will leave the issue open in case you want to add a LICENSE file to the repository but feel free to close it anytime. Keep up the great work!

**Comment by ctrueden** [comment]
Thank you for the clarification, guys. I have updated the repository accordingly to indicate that the license is GPL v3+.
